Added API
Arturgouveia1970/My_Blog_App pull request #14
Opened 2022-09-08 16:14 UTC by Arturgouveia1970

## In this PR we:
- Created an API endpoint to list all posts for a user.
- Created an API endpoint to list all comments for a user's post.
- Created an API endpoint to add a comment to a post.
- Added authentication to your API endpoints.

2022-09-09 13:45 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Arturgouveia1970, and @RWUBAKWANAYO👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 13:45 UTC, thecodechaser commented on config/routes.rb
> +  end
- [ ] You did a great job creating endpoints but you missed a project requirement to add authentication to your API endpoints. Please make sure to add authentication to your API endpoints and users should not be able to access the data without authenticating themselves.
  - I would suggest adding API endpoints to log in and signup for users.

2022-09-09 14:45 UTC, RWUBAKWANAYO commented on config/routes.rb
> +  end
Hi @thecodechaser,
I really appreciate the feedback you provide on this PR.
I would like to ask you more about how we missed authentication to our API because on our side the user can not access the API without signing in or registering.
Thank you once. I would appreciate your immediate attention to this message.

2022-09-09 18:19 UTC, whiz25 approved these changes
Hi @Arturgouveia1970, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉 🎉 🎉 
- Nice work making the requested changes

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 18:28 UTC, merged

2022-09-10 12:37 UTC, sinansevgi reviewed
Hello @RWUBAKWANAYO  👋,

_This is an additional review as a result of the second opinion request._

We are sorry for the late reply. I saw that your issue has been resolved. Is there anything else you need help with?

Keep rocking 🚀!