Validation specs
Arturgouveia1970/My_Blog_App pull request #3
Opened 2022-08-26 16:58 UTC by Arturgouveia1970

In this PR:
- Created model spec tests
- Created validation for classes

2022-08-26 23:24 UTC, MahmoudBakr23 reviewed
# Hi @Arturgouveia1970  😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission

- Thank you for your honest and sincere request. Great work you've done so far on this project, please check out this [article ](https://docs.rubocop.org/rubocop/usage/auto_correct.html)  in the rubocop command to fix and detect the errors

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._ 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

2022-08-27 05:25 UTC, Arturgouveia1970 commented
Hello @MahmoudBakr23, I appreciate that that you cannot review this project, but what I am really asking is help to solve this rubocop issue. I wonder if you can help!? RespectfullyArtur Enviado do meu telemóvel Huawei.-------- Mensagem original --------De: Mahmoud Bakr ***@***.***>Data: sábado, 27 de agosto de 2022, 00:25Para: Arturgouveia1970/My_Blog_App ***@***.***>Cc: Artur Gouveia ***@***.***>, Mention ***@***.***>Assunto: Re: [Arturgouveia1970/My_Blog_App] Validation specs (PR #3)

@MahmoudBakr23 commented on this pull request.



Hi @Arturgouveia1970  😃,

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

**Invalid Submission

Thank you for your honest and sincere request. Great work you've done so far on this project, please check out this article   in the rubocop command to fix and detect the errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready. 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.



Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.



Invalid Code Review Request does not count into the code reviews limit.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-08-27 11:37 UTC, medaminedev66 requested changes
Hi @Arturgouveia1970  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The repo looks professional
- There are no linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 11:37 UTC, medaminedev66 commented on spec/models/post_spec.rb
> +end
- [ ] Great job adding validation tests for the Post model. You should be aware that if the Post model contains no validations, validation tests are worthless. Check out [this link](https://guides.rubyonrails.org/active_record_validations.html) to learn how to add validations to the models.
- [ ] As requested in the project requirements, any custom methods in the models should have a corresponding unit test. Kindly add a unit test for `update_users_posts_counter` method.

2022-08-27 11:37 UTC, medaminedev66 commented on spec/models/user_spec.rb
> +end
- [ ] Following the project requirements, any custom methods in the models' User, Like, and Comment should have a corresponding unit test.

2022-08-27 11:37 UTC, medaminedev66 commented on spec/models/user_spec.rb
> +end
- [ ] I'm still confused about exactly what you're testing in the user_spec file. It might be nicer to include some description of what you hope to accomplish with these few tests. Remember that our goal is to add validation tests for our models. I recommend using `Validation tests` such as the example below:
```ruby
describe 'validations' do
  it { should validate_presence_of(:name) }
end
```

2022-08-27 11:37 UTC, medaminedev66 commented on app/models/like.rb
>      post.increment!(:likes_counter)
- Following the project requirements, `User` and `Like` models should have validations:
- User:
   * Name must not be blank
   * PostsCounter must be an integer greater than or equal zero.
- Post:
   * Title must not be blank.
   * Title must not exceed 250 characters.
   * CommentsCounter must be an integer greater than or equal zero.
   * LikesCounter must be an integer greater than or equal zero.

You may check out [this link](https://guides.rubyonrails.org/active_record_validations.html) to learn how to add validations to the models.

2022-08-27 15:00 UTC, medaminedev66 requested changes
Hi @MahmoudBakr23 😃,

Great work on working on the requested changes👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- The validations have been added to `Post` and `User` models.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 18:59 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @Arturgouveia1970, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 18:59 UTC, Mihndim2020 commented on spec/models/user_spec.rb
> +  #   end
- [OPTIONAL] Please kindly remove `commented code` from your `code base`, as it makes your `code base` dirty and less readable. To make sure that your codebase is always clean, always remember to remove commented-codes.

2022-08-27 19:07 UTC, merged